development:
  adapter: mysql2
  encoding: utf8
  database: rails_dev
  username: root
  password: sigma@123
  host: 127.0.0.1
  port: 3306

test:
  adapter: mysql2
  encoding: utf8
  database: rails_test
  username: root
  password: sigma@123
  host: 127.0.0.1
  port: 3306